survOutUI <- function(id) {
  ns <- NS(id)
  
  tagList(
    
      # h2(HTML("<strong>Survival Outcomes</strong>")),
      uiOutput(ns("surv_title")),
      uiOutput(ns("surv_section_header")),
      hr(style = "border-top: 3px solid #044d48;"),
      br(),
    
    fluidRow(
        column(3,
               div(style = "height: 85px;"),
               bslib::card(
                 height = 300,
                 # class = "sky-bkg",
                 style = "background-color: #e8eeed;
                          color: #044d48;
                          padding-right: 5%;
                          padding-left: 5%;
                          padding-top: 10%;
                          padding-bottom: 10%;
                          border-radius: 15px;  
                          box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); 
                          align-content:center !important;",
                 DT::DTOutput(ns("median_tbl"))
               )
              ),
        column(9,
               plotOutput(ns("km_plot_tbl"), height = "650px"),
               br(),
               div(
                 style = "padding-left:95px;",
                 p(HTML("<strong>Notes:</strong>")),
                 p("[1] The probabilistic weight cutoff for the Augmented Cohort is selected on the 'Eligibility Probabilty' Screen."),
                 p("[2] The survival probabilities for the Augmented cohort are weighted by the probabilistic weights generated by the Random Forest Model.")
               )
        )
    )
  )
}

survOutServer <- function(id, report_object, sectionHeader, survOutcomes, surv_outcome) {
  moduleServer(id, function(input, output, session) {
    
    output$surv_title <- renderUI({
      h2(HTML(sprintf("<strong>%s</strong>", surv_outcome)))
    })
  
    # text describing selected trial/real-world data set/cohort
    output$surv_section_header <- renderUI({
      ns <- session$ns
      sectionHeader()
    })
    
    output$km_plot_tbl <- renderPlot({
      ns <- session$ns
      survOutcomes()$km_plot_tbl
    })
    
    output$median_tbl <- DT::renderDT({
      ns <- session$ns
      survOutcomes()$median_tbl
    })
  })
}
